export class ConstantesSecciones {
    static TIPO_DECLARACION = 'TIPO_DECLARACION';
    static CONDOMINOS = 'CONDOMINOS';
    static ALQUILERES_PAGADOS = 'ALQUILERES_PAGADOS';
    static ATRIBUCION_GASTOS = 'ATRIBUCION_GASTOS';
    static OTROS_INGRESOS = 'OTROS_INGRESOS';
    static PRIMERA_CATEGORIA = 'PRIMERA_CATEGORIA';
    static SEGUNDA_CATEGORIA = 'SEGUNDA_CATEGORIA';
    static FUENTE_EXTRANJERA = 'FUENTE_EXTRANJERA';
    static DETERMINACION_DEUDA = 'DETERMINACION_DEUDA';
}
