import { ConstantesCasillas } from '@rentas/shared/constantes';

export abstract class CasillasUtil {
    CODIGO_TIPO_CASILLA_CON_ASISTENTE = ConstantesCasillas.CODIGO_TIPO_CASILLA_CON_ASISTENTE;
     CODIGO_TIPO_CASILLA_CALCULADA = ConstantesCasillas.CODIGO_TIPO_CASILLA_CALCULADA;
     CODIGO_TIPO_CASILLA_EDITABLE_TEXTO_SIN_FORMATO = ConstantesCasillas.CODIGO_TIPO_CASILLA_EDITABLE_TEXTO_SIN_FORMATO;
     CODIGO_TIPO_CASILLA_EDITABLE_FORMATO_NUMERICO = ConstantesCasillas.CODIGO_TIPO_CASILLA_EDITABLE_FORMATO_NUMERICO;

     CODIGO_TIPO_CONTROL_TEXTBOX = ConstantesCasillas.CODIGO_TIPO_CONTROL_TEXTBOX;
     CODIGO_TIPO_CONTROL_COMBOBOX = ConstantesCasillas.CODIGO_TIPO_CONTROL_COMBOBOX;
     CODIGO_TIPO_CONTROL_RADIOBUTTON = ConstantesCasillas.CODIGO_TIPO_CONTROL_RADIOBUTTON;
     CODIGO_TIPO_CONTROL_CHECKBOX = ConstantesCasillas.CODIGO_TIPO_CONTROL_CHECKBOX;

     FORMATO_MONTO = ConstantesCasillas.FORMATO_MONTO;
     FORMATO_NUMERICO = ConstantesCasillas.FORMATO_NUMERICO;
     FORMATO_PORCENTAJE = ConstantesCasillas.FORMATO_PORCENTAJE;
     FORMATO_ALFANUMERICO = ConstantesCasillas.FORMATO_ALFANUMERICO;
}